---
- hosts: capsules
  vars_files:
  - vars.yml
  vars:
    capsule_install: true
    tower_install: true
    capsule_upgrade: false
  roles:
  - create_certs
  - bootstrap
  - repo_enable
  - capsule_install
  - capsule_check
